name: speakly
description: "Speakly - Secure Next-Gen Messenger"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI, иконки и шрифты
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.3

  # Хранилище и утилиты
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
